# Generated by Django 4.2.13 on 2024-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_food_foodcategory_foodnutrient_nutrient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodnutrient',
            name='amount',
        ),
        migrations.AddField(
            model_name='food',
            name='calories_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodnutrient',
            name='amount_100g',
            field=models.FloatField(default=0),
        ),
    ]
